import type { Task } from "@entities/task/model/types";

export const testTasks: Task[] = [
  {
    id: "2",
    title: "Исправление стилей в Safari",
    description: "Кнопки отображаются некорректно в браузере Safari",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: "bug",
    status: "in_progress",
    priority: "medium",
  },
  {
    id: "3",
    title: "Мелкие опечатки в интерфейсе",
    description: "Исправить орфографические ошибки в подсказках",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "bug",
    status: "done",
    priority: "low",
  },
  {
    id: "4",
    title: "Темная тема приложения",
    description: "Реализовать переключение между светлой и темной темами",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "feature",
    status: "in_progress",
    priority: "high",
  },
  {
    id: "5",
    title: "Экспорт задач в PDF",
    description: "Добавить возможность экспорта списка задач в PDF формат",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "feature",
    status: "todo",
    priority: "medium",
  },
  {
    id: "6",
    title: "Уведомления по email",
    description: "Отправка напоминаний о приближающихся дедлайнах",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "feature",
    status: "done",
    priority: "low",
  },
  {
    id: "7",
    title: "API документация",
    description: "Создать подробную документацию для REST API",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "documentation",
    status: "todo",
    priority: "medium",
  },
  {
    id: "8",
    title: "Руководство пользователя",
    description: "Написать инструкцию по использованию приложения",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "documentation",
    status: "in_progress",
    priority: "low",
  },
  {
    id: "9",
    title: "Оптимизация компонентов React",
    description: "Рефакторинг компонентов для улучшения производительности",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "refactor",
    status: "todo",
    priority: "high",
  },
  {
    id: "10",
    title: "Унификация стилей CSS",
    description:
      "Привести все стили к единому стандарту и удалить дублирования",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "refactor",
    status: "done",
    priority: "medium",
  },
  {
    id: "11",
    title: "E2E тесты для авторизации",
    description: "Написать end-to-end тесты для процесса регистрации и входа",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "test",
    status: "in_progress",
    priority: "high",
  },
  {
    id: "12",
    title: "Unit тесты для API",
    description: "Покрыть тестами все эндпоинты REST API",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date(),
    category: "test",
    status: "todo",
    priority: "low",
  },
  {
    id: "13",
    title: "Критический баг в авторизации",
    description: "Пользователи не могут войти в систему через Google OAuth",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: "bug",
    status: "todo",
    priority: "high",
  },
];